### ISSUE TITLE
Awesome project and feature how many time spent on task

### ISSUE THREAD

**Issue by evilebottnawi** [coderaiser/redrun#1]
I am from https://habrahabr.ru/post/308930/ :smile: what about add option (maube `-t`) for how many time spent on task, i have same issue in `npm-run-all` https://github.com/mysticatea/npm-run-all/issues/46.

**Comment by coderaiser** [comment]
Thank you, I'll think about it. Actually it is not main purpose of `redrun` and OS compatibility should be counted. Do you have any ideas how to do this right?

**Comment by coderaiser** [comment]
@evilebottnawi could you tell me please why don't you like to use `time`?

**Comment by evilebottnawi** [comment]
@coderaiser not human readable, i think we can look as this do task runners, example gulp or grunt with OS compatibility

**Comment by coderaiser** [comment]
Actually any program that behave like `time` could be used for this purpose. I don't think that it should be built-in feature of `redrun`.
