### ISSUE TITLE
Can't throw error code on any command, that not last, on parallel exec

### ISSUE THREAD

**Issue by darky** [coderaiser/redrun#10]
* **Version** (`redrun -v`): 7.1.5
* **Node Version** `node -v`: 11.11.0
* **OS** (`uname -a` on Linux): Linux 4.19.28-1-MANJARO
* **Used Command Line Parameters**: redrun -p one two three

For example, if command `one` or `two` exit with non-zero code, `redrun` exit with zero code.
It works properly only with last `three` command

**Comment by coderaiser** [comment]
Could you please show me example of `scripts section`.

**Comment by darky** [comment]
It any command, on my case it `tslint`, `tsc`

**Comment by coderaiser** [comment]
How do you run `redrun`?

**Comment by darky** [comment]
`npm run some-command`, where some-command is `redrun -p one two three`

**Comment by coderaiser** [comment]
The thing is when you using parallel execution result command looks this way:

```sh
coderaiser@cloudcmd:~$ redrun -p one two three
> ./one.js & ./two.js & ./three.js
```
[& symbol](https://en.wikipedia.org/wiki/Bash_(Unix_shell)#Process_management) used for parallel execution. [execSync](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options) used to run this command with help of default shell (`bash` on linux), and exit with code received from `execSync`. If you need more control over exit code use `--series` execution, which will be converted to: `&&`, and this will result in exit code you need.
