### ISSUE TITLE
yarn?

### ISSUE THREAD

**Issue by fobdy** [coderaiser/redrun#11]
Any thoughts on `yarn`?

**Comment by coderaiser** [comment]
What thoughts do you mean :)? `npm scripts` is a built feature of `npm`, are you using `yarn scripts`? What benefits it gives you? `yarn` should also be installed independently, and `npm` is always here :).

And also look around [madrun](https://github.com/coderaiser/madrun) it gives you oportunity write scripts in `JavaScript`, no `JSON` :).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
