### ISSUE TITLE
Doesn't work with dotted script names

### ISSUE THREAD

**Issue by likerRr** [coderaiser/redrun#2]
I have `npm` script which name "dev.compile" and seems like it can't be run by `redrun dev.compile`:

`One of scripts not found: dev.compile`

**Comment by coderaiser** [comment]
Thank you, I'll think how to fix it.

**Comment by coderaiser** [comment]
Fixed with aa18f79, landed in [v5.5.2](https://github.com/coderaiser/redrun/releases/tag/v5.5.2).
