### ISSUE TITLE
Populating the same set of environment variables that npm run does

### ISSUE THREAD

**Issue by zkochan** [coderaiser/redrun#3]
Awesome project!

I am one of the maintainers of [pnpm](https://github.com/rstacruz/pnpm/) and I think it would be awesome to use redrun instead of `npm run` to make pnpm even faster.

However, currently redrun does not populate all the env variables that `npm run` does. For instance, this won't work with redrun:

```
{
    "one": "npm run two",
    "two": "npm run three",
    "three": "printenv npm_lifecycle_event"
}
```

**Comment by coderaiser** [comment]
Thank you, [$npm_lifecycle_event](https://docs.npmjs.com/misc/scripts#current-lifecycle-event) it is interesting feature, but in case of `redrun` all scripts will be transformed in one line:

```sh
printenv npm_lifecycle_event
```
Which should be `three` I think. But what if in `scripts` would be a couple such variables:

```json
{
    "one": "redrun two three",
    "two": "printenv npm_lifecycle_event",
    "three": "printenv npm_lifecycle_event"
}
```

In case of `npm` it will show:

```sh
two
three
```

But in case of `redrun` it will be such string:

```sh
printenv npm_lifecycle_event && printenv npm_lifecycle_event
```

So the only way it could be solved is setting `$npm_lifecycle_event` variables before using it, so scripts should be transformed to something like this:

```sh
npm_lifecycle_event=two printenv npm_lifecycle_event && npm_lifecycle_event=three printenv npm_lifecycle_event
```

Should it be [at the beginning of every script](https://medium.com/@brianhan/use-this-npm-variable-as-a-flag-for-your-build-scripts-31069f5e2e57#.453why46p) or just when `$npm_lifecycle_event` is present in the body of the script?

It is an interesting idea, but I think it would create a lot noise in the output of `redrun`: on every step this variable should be set up. 

Can you tell me please what is your use case?

**Comment by zkochan** [comment]
`pnpm` is a fast implementation of `npm install`. It runs the package's lifecycle events during installation (like preinstall, postinstall, prebublish). It uses `npm run` to run these events. First it was running them directly via `child_process`, but we discovered that some packages were failing because they were relying on the environment variables defined by `npm run` (there are more of those, not just `npm_lifecycle_event`).

So my use case is to have the same set of variables as when `npm run` is executed.

I think `redrun` to `npm run` is what `pnpm` is to `pnpm install` and it would be logical for pnpm to use a better implementation of `npm run`

**Comment by coderaiser** [comment]
I dont't know if `redrun` will feet you needs completely. The thing is when you execute `redrun install` it searches `install` script, when can't find it shows error. When can find, it searches `preinstall` and `postinstall` and combines it to one command. So it is one step, not 3 separeted.

About `npm_lifecycle_event` I do not know how make this variable works for whole script in the same way on `Windows` and `Linux`. This way wouldn't work:

```sh
npm_lifecycle_event=install ls && echo $npm_lifecycle_event
```
So it looks like we should add env variable to every command, or add `functions` which is not portable between shells of different Operation Systems. Do you have any ideas how to deal with it?

**Comment by zkochan** [comment]
For the env variables we can use [cross-env](https://www.npmjs.com/package/cross-env).

The first issue about merging scripts to one command, I think shouldn't be a problem, but we'll see.

**Comment by coderaiser** [comment]
Unfortunately `cross-env` does not resolve issue related to [running a couple commands with one environment variable](https://www.npmjs.com/package/cross-env#known-limitations).

**Comment by zkochan** [comment]
I see... I'll close this for now, because seems like it is too hard to implement and the benefits are not so big. But I'll look into it later
