### ISSUE TITLE
Support per-script arguments

### ISSUE THREAD

**Issue by tlvince** [coderaiser/redrun#4]
In npm-run-all, you can pass [script-specific arguments](https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md#run-with-arguments). AFAICT, redrun only supports passing arguments to all scripts.

So e.g in the following…

```json
{
  "clean": "rm -rf build && mkdir build",
  "build": "babel",
  "build:watch": "redrun clean build -- --watch"
}
```

… redrun will expand `build:watch` to `rm -rf build && mkdir build --watch && babel --watch`, which means an undesirable `--watch` dir is created.

Adding an intermediary script fixes this, but it's a little verbose:

```json
{
  "clean": "rm -rf build && mkdir build",
  "build": "babel",
  "build:watch": "redrun build -- --watch",
  "watch": "redrun clean build:watch"
}
```

Something like the following would be handy:

```json
{
  "clean": "rm -rf build && mkdir build",
  "build": "babel",
  "build:watch": "redrun clean 'build -- --watch'"
}
```

… which expands to `rm -rf build && mkdir build && babel --watch`.

**Comment by coderaiser** [comment]
What a great idea for a pull request :).

**Comment by coderaiser** [comment]
Closed due to long time of inactivity.
